name: Provision of Ec2 instance and configuration

on:
  push:
    branches: [ "main" ]

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: "3.10" }

    - name: Install ansible
      run: |
        pip install ansible boto3 botocore
        ansible-galaxy collection install amazon.aws

    - name: AWS creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem

    - name: Run playbook
      run: |
        ansible-playbook ./ansible/playbooks/provision_and_configure_server.yml \
        -e "aws_region=${{ secrets.AWS_REGION }}" \
        -e "ec2_key_name=${{ secrets.EC2_KEY_NAME }}" \
        -e "ec2_instance_type=${{ secrets.EC2_INSTANCE_TYPE }}" \
        -e "ec2_ami_id=${{ secrets.EC2_AMI_ID }}" \
        -e "ec2_ssh_key_path=~/.ssh/ec2_key.pem" \
        -e "PORT=${{ secrets.PORT }}" \
        -e "MONGO_URI='${{ secrets.MONGO_URI }}'" \
        -e "JWT_SECRET='${{ secrets.JWT_SECRET }}'" \
        -e "ADMIN_INVITE_CODE='${{ secrets.ADMIN_INVITE_CODE }}'" \
        -e "VITE_API_URL=${{ secrets.VITE_API_URL }}"
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
